id: P007846
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1656
  title: གསུང་འབུམ། བློ་བཟང་རྒྱལ་མཚན་སེངྒེ
  author: ''
  volumes:
    3c54ffe65a9145f289a24216c0f538ca:
      image_group_id: I1KG1730
      title: ''
      volume_number: 1
      total_pages: 461
    e9a75de662c44a00b52165fa844b24b0:
      image_group_id: I1KG1731
      title: ''
      volume_number: 2
      total_pages: 638
    704ed7b12803444f93d5e0deecc4c463:
      image_group_id: I1KG1732
      title: ''
      volume_number: 3
      total_pages: 592
    54d685c77bb143beb75bee3cf57c74c7:
      image_group_id: I1KG1733
      title: ''
      volume_number: 4
      total_pages: 588
    8a3bc4d55fb348b39679d370f0b7dad9:
      image_group_id: I1KG1734
      title: ''
      volume_number: 5
      total_pages: 618
    e11667a2e01643cb8f171a2e5c158732:
      image_group_id: I1KG1735
      title: ''
      volume_number: 6
      total_pages: 474
    91d6f6382c0f4e54936ec2b71c0b6176:
      image_group_id: I1KG1736
      title: ''
      volume_number: 7
      total_pages: 376
    94e17d2130f54cc08ba81d7f212c0fef:
      image_group_id: I1KG1737
      title: ''
      volume_number: 8
      total_pages: 718
ebook_metadata:
  title: གསུང་འབུམ། བློ་བཟང་རྒྱལ་མཚན་སེངྒེ
  author: ''
  sku: P007846
  cover: cover.jpg
  layers:
  - pagination
