id: I0A928900
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:16:08+00:00'
last_modified: '2022-06-09T06:31:58.443662+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1656
  title: གསུང་འབུམ། བློ་བཟང་རྒྱལ་མཚན་སེངྒེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9C9D:
      image_group_id: I1KG1730
      title: Volume 1 of gsung 'bum/_blo bzang rgyal mtshan seng+ge
      total_pages: 461
      order: 1
      base_file: 9C9D.txt
    '1101':
      image_group_id: I1KG1731
      title: Volume 2 of gsung 'bum/_blo bzang rgyal mtshan seng+ge
      total_pages: 638
      order: 2
      base_file: 1101.txt
    91E9:
      image_group_id: I1KG1732
      title: Volume 3 of gsung 'bum/_blo bzang rgyal mtshan seng+ge
      total_pages: 592
      order: 3
      base_file: 91E9.txt
    '4479':
      image_group_id: I1KG1733
      title: Volume 4 of gsung 'bum/_blo bzang rgyal mtshan seng+ge
      total_pages: 588
      order: 4
      base_file: 4479.txt
    E7F4:
      image_group_id: I1KG1734
      title: Volume 5 of gsung 'bum/_blo bzang rgyal mtshan seng+ge
      total_pages: 618
      order: 5
      base_file: E7F4.txt
    2FCD:
      image_group_id: I1KG1735
      title: Volume 6 of gsung 'bum/_blo bzang rgyal mtshan seng+ge
      total_pages: 474
      order: 6
      base_file: 2FCD.txt
    BA13:
      image_group_id: I1KG1736
      title: Volume 7 of gsung 'bum/_blo bzang rgyal mtshan seng+ge
      total_pages: 376
      order: 7
      base_file: BA13.txt
    B19F:
      image_group_id: I1KG1737
      title: Volume 8 of gsung 'bum/_blo bzang rgyal mtshan seng+ge
      total_pages: 718
      order: 8
      base_file: B19F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
