id: I0A928900
legacy_id: P007846
ocr_import_info:
  bdrc_scan_id: W1KG1656
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T20:10:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:36:25.156342+00:00'
last_modified: 2022-08-31 16:38:35.628947
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG1656
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG1656
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་རྒྱལ་མཚན་སེངྒེ
  author: གཙོས་ཁྲི་སྤྲུལ ༠༢་བློ་བཟང་རྒྱལ་མཚན་སེངྒེ
statistics:
  ocr_word_mean_confidence_index: 0.6852366356608517
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1KG1733:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1733
      total_pages: 588
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG1733.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6982985787091825
    legacy_id: v004
  I1KG1730:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1730
      total_pages: 461
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1730.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7503397109922116
    legacy_id: v001
  I1KG1734:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1734
      total_pages: 618
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG1734.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6731931984020427
    legacy_id: v005
  I1KG1732:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1732
      total_pages: 592
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG1732.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7013901809424982
    legacy_id: v003
  I1KG1737:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1737
      total_pages: 718
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG1737.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6823384889917962
    legacy_id: v008
  I1KG1735:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1735
      total_pages: 474
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG1735.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6554810575645365
    legacy_id: v006
  I1KG1736:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1736
      total_pages: 376
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG1736.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6941573845932332
    legacy_id: v007
  I1KG1731:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1731
      total_pages: 638
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG1731.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6359551841807298
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
